// Code generated by protoc-gen-go. DO NOT EDIT.
// source: voltha_protos/schema.proto

package schema

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Contains the name and content of a *.proto file
type ProtoFile struct {
	FileName             string   `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	Proto                string   `protobuf:"bytes,2,opt,name=proto,proto3" json:"proto,omitempty"`
	Description          []byte   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtoFile) Reset()         { *m = ProtoFile{} }
func (m *ProtoFile) String() string { return proto.CompactTextString(m) }
func (*ProtoFile) ProtoMessage()    {}
func (*ProtoFile) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d785a7d5fd3f7a9, []int{0}
}

func (m *ProtoFile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoFile.Unmarshal(m, b)
}
func (m *ProtoFile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoFile.Marshal(b, m, deterministic)
}
func (m *ProtoFile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoFile.Merge(m, src)
}
func (m *ProtoFile) XXX_Size() int {
	return xxx_messageInfo_ProtoFile.Size(m)
}
func (m *ProtoFile) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoFile.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoFile proto.InternalMessageInfo

func (m *ProtoFile) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *ProtoFile) GetProto() string {
	if m != nil {
		return m.Proto
	}
	return ""
}

func (m *ProtoFile) GetDescription() []byte {
	if m != nil {
		return m.Description
	}
	return nil
}

// Proto files and compiled descriptors for this interface
type Schemas struct {
	// Proto files
	Protos []*ProtoFile `protobuf:"bytes,1,rep,name=protos,proto3" json:"protos,omitempty"`
	// Proto file name from which swagger.json shall be generated
	SwaggerFrom string `protobuf:"bytes,2,opt,name=swagger_from,json=swaggerFrom,proto3" json:"swagger_from,omitempty"`
	// Proto file name from which yang schemas shall be generated
	YangFrom             string   `protobuf:"bytes,3,opt,name=yang_from,json=yangFrom,proto3" json:"yang_from,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Schemas) Reset()         { *m = Schemas{} }
func (m *Schemas) String() string { return proto.CompactTextString(m) }
func (*Schemas) ProtoMessage()    {}
func (*Schemas) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d785a7d5fd3f7a9, []int{1}
}

func (m *Schemas) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Schemas.Unmarshal(m, b)
}
func (m *Schemas) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Schemas.Marshal(b, m, deterministic)
}
func (m *Schemas) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Schemas.Merge(m, src)
}
func (m *Schemas) XXX_Size() int {
	return xxx_messageInfo_Schemas.Size(m)
}
func (m *Schemas) XXX_DiscardUnknown() {
	xxx_messageInfo_Schemas.DiscardUnknown(m)
}

var xxx_messageInfo_Schemas proto.InternalMessageInfo

func (m *Schemas) GetProtos() []*ProtoFile {
	if m != nil {
		return m.Protos
	}
	return nil
}

func (m *Schemas) GetSwaggerFrom() string {
	if m != nil {
		return m.SwaggerFrom
	}
	return ""
}

func (m *Schemas) GetYangFrom() string {
	if m != nil {
		return m.YangFrom
	}
	return ""
}

func init() {
	proto.RegisterType((*ProtoFile)(nil), "schema.ProtoFile")
	proto.RegisterType((*Schemas)(nil), "schema.Schemas")
}

func init() { proto.RegisterFile("voltha_protos/schema.proto", fileDescriptor_9d785a7d5fd3f7a9) }

var fileDescriptor_9d785a7d5fd3f7a9 = []byte{
	// 327 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x51, 0xdd, 0x4e, 0xc2, 0x30,
	0x14, 0xce, 0x20, 0x82, 0x2b, 0x18, 0x62, 0x63, 0xcc, 0x32, 0xbc, 0x98, 0x5c, 0xe1, 0x85, 0x6d,
	0x02, 0x6f, 0x60, 0x02, 0xde, 0x18, 0x63, 0x20, 0xf1, 0xc2, 0x1b, 0x2c, 0xa3, 0x94, 0x26, 0xeb,
	0xce, 0xd2, 0x15, 0x0c, 0xb7, 0xbe, 0x82, 0x8f, 0xe6, 0x2b, 0xf8, 0x20, 0xa6, 0x3b, 0xc5, 0x78,
	0xb7, 0xef, 0xa7, 0x3b, 0xdf, 0xf9, 0x0e, 0x49, 0x0f, 0x50, 0xb8, 0x9d, 0x58, 0x55, 0x16, 0x1c,
	0xd4, 0xbc, 0xce, 0x77, 0xd2, 0x08, 0xd6, 0x20, 0xda, 0x41, 0x94, 0xde, 0x28, 0x00, 0x55, 0x48,
	0x2e, 0x2a, 0xcd, 0x45, 0x59, 0x82, 0x13, 0x4e, 0x43, 0x59, 0xa3, 0x2b, 0x1d, 0x06, 0xb5, 0x41,
	0xeb, 0xfd, 0x96, 0x4b, 0x53, 0xb9, 0x23, 0x8a, 0xa3, 0x77, 0x12, 0xbf, 0xf8, 0x8f, 0xb9, 0x2e,
	0x24, 0x1d, 0x92, 0x78, 0xab, 0x0b, 0xb9, 0x2a, 0x85, 0x91, 0x49, 0x94, 0x45, 0xe3, 0x78, 0x71,
	0xee, 0x89, 0x67, 0x61, 0x24, 0xbd, 0x22, 0x67, 0xcd, 0x93, 0xa4, 0xd5, 0x08, 0x08, 0x68, 0x46,
	0x7a, 0x1b, 0x59, 0xe7, 0x56, 0x57, 0x7e, 0x64, 0xd2, 0xce, 0xa2, 0x71, 0x7f, 0xf1, 0x9f, 0x1a,
	0x39, 0xd2, 0x5d, 0x36, 0x31, 0x6b, 0x7a, 0x47, 0x3a, 0xb8, 0x46, 0x12, 0x65, 0xed, 0x71, 0x6f,
	0x72, 0xc9, 0xc2, 0x3a, 0x7f, 0x11, 0x16, 0xc1, 0x40, 0x6f, 0x49, 0xbf, 0xfe, 0x10, 0x4a, 0x49,
	0xbb, 0xda, 0x5a, 0x30, 0x61, 0x68, 0x2f, 0x70, 0x73, 0x0b, 0xc6, 0xa7, 0x3d, 0x8a, 0x52, 0xa1,
	0xde, 0xc6, 0xb4, 0x9e, 0xf0, 0xe2, 0xe4, 0x95, 0x5c, 0xe0, 0xd4, 0xa5, 0xb4, 0x07, 0x9d, 0x4b,
	0x3a, 0x23, 0xf1, 0xa3, 0x74, 0xc8, 0xd1, 0x6b, 0x86, 0x9d, 0xb0, 0x53, 0x27, 0x6c, 0xe6, 0x3b,
	0x49, 0x07, 0xa7, 0x40, 0x21, 0xf1, 0x68, 0xf0, 0xf9, 0xfd, 0xf3, 0xd5, 0x8a, 0x69, 0x37, 0x14,
	0xff, 0xf0, 0x44, 0x52, 0xb0, 0x8a, 0x41, 0x25, 0xcb, 0x1c, 0xec, 0x86, 0xe1, 0x75, 0xc2, 0xb3,
	0x37, 0xa6, 0xb4, 0xdb, 0xed, 0xd7, 0x2c, 0x07, 0xc3, 0x4f, 0x16, 0x8e, 0x96, 0xfb, 0x70, 0xc0,
	0xc3, 0x94, 0x2b, 0x08, 0x7f, 0x5b, 0xe3, 0xb6, 0xd3, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa7,
	0xce, 0x1c, 0xca, 0xe5, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SchemaServiceClient is the client API for SchemaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SchemaServiceClient interface {
	// Return active grpc schemas
	GetSchema(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Schemas, error)
}

type schemaServiceClient struct {
	cc *grpc.ClientConn
}

func NewSchemaServiceClient(cc *grpc.ClientConn) SchemaServiceClient {
	return &schemaServiceClient{cc}
}

func (c *schemaServiceClient) GetSchema(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Schemas, error) {
	out := new(Schemas)
	err := c.cc.Invoke(ctx, "/schema.SchemaService/GetSchema", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SchemaServiceServer is the server API for SchemaService service.
type SchemaServiceServer interface {
	// Return active grpc schemas
	GetSchema(context.Context, *empty.Empty) (*Schemas, error)
}

func RegisterSchemaServiceServer(s *grpc.Server, srv SchemaServiceServer) {
	s.RegisterService(&_SchemaService_serviceDesc, srv)
}

func _SchemaService_GetSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchemaServiceServer).GetSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schema.SchemaService/GetSchema",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchemaServiceServer).GetSchema(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _SchemaService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "schema.SchemaService",
	HandlerType: (*SchemaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSchema",
			Handler:    _SchemaService_GetSchema_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "voltha_protos/schema.proto",
}
