// Code generated by protoc-gen-go. DO NOT EDIT.
// source: voltha_protos/bbf_fiber_wavelength_profile_body.proto

package bbf_fiber

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/opencord/voltha-protos/go/common"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type WavelengthProfileData struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	UpstreamChannelid    uint32   `protobuf:"varint,2,opt,name=upstream_channelid,json=upstreamChannelid,proto3" json:"upstream_channelid,omitempty"`
	DownstreamChannelid  uint32   `protobuf:"varint,3,opt,name=downstream_channelid,json=downstreamChannelid,proto3" json:"downstream_channelid,omitempty"`
	DownstreamWavelength uint32   `protobuf:"varint,4,opt,name=downstream_wavelength,json=downstreamWavelength,proto3" json:"downstream_wavelength,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WavelengthProfileData) Reset()         { *m = WavelengthProfileData{} }
func (m *WavelengthProfileData) String() string { return proto.CompactTextString(m) }
func (*WavelengthProfileData) ProtoMessage()    {}
func (*WavelengthProfileData) Descriptor() ([]byte, []int) {
	return fileDescriptor_878482202d379581, []int{0}
}

func (m *WavelengthProfileData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WavelengthProfileData.Unmarshal(m, b)
}
func (m *WavelengthProfileData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WavelengthProfileData.Marshal(b, m, deterministic)
}
func (m *WavelengthProfileData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WavelengthProfileData.Merge(m, src)
}
func (m *WavelengthProfileData) XXX_Size() int {
	return xxx_messageInfo_WavelengthProfileData.Size(m)
}
func (m *WavelengthProfileData) XXX_DiscardUnknown() {
	xxx_messageInfo_WavelengthProfileData.DiscardUnknown(m)
}

var xxx_messageInfo_WavelengthProfileData proto.InternalMessageInfo

func (m *WavelengthProfileData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *WavelengthProfileData) GetUpstreamChannelid() uint32 {
	if m != nil {
		return m.UpstreamChannelid
	}
	return 0
}

func (m *WavelengthProfileData) GetDownstreamChannelid() uint32 {
	if m != nil {
		return m.DownstreamChannelid
	}
	return 0
}

func (m *WavelengthProfileData) GetDownstreamWavelength() uint32 {
	if m != nil {
		return m.DownstreamWavelength
	}
	return 0
}

type WavelengthProfile struct {
	WavelengthProfileData []*WavelengthProfileData `protobuf:"bytes,1,rep,name=wavelength_profile_data,json=wavelengthProfileData,proto3" json:"wavelength_profile_data,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}                 `json:"-"`
	XXX_unrecognized      []byte                   `json:"-"`
	XXX_sizecache         int32                    `json:"-"`
}

func (m *WavelengthProfile) Reset()         { *m = WavelengthProfile{} }
func (m *WavelengthProfile) String() string { return proto.CompactTextString(m) }
func (*WavelengthProfile) ProtoMessage()    {}
func (*WavelengthProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_878482202d379581, []int{1}
}

func (m *WavelengthProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WavelengthProfile.Unmarshal(m, b)
}
func (m *WavelengthProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WavelengthProfile.Marshal(b, m, deterministic)
}
func (m *WavelengthProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WavelengthProfile.Merge(m, src)
}
func (m *WavelengthProfile) XXX_Size() int {
	return xxx_messageInfo_WavelengthProfile.Size(m)
}
func (m *WavelengthProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_WavelengthProfile.DiscardUnknown(m)
}

var xxx_messageInfo_WavelengthProfile proto.InternalMessageInfo

func (m *WavelengthProfile) GetWavelengthProfileData() []*WavelengthProfileData {
	if m != nil {
		return m.WavelengthProfileData
	}
	return nil
}

func init() {
	proto.RegisterType((*WavelengthProfileData)(nil), "bbf_fiber.WavelengthProfileData")
	proto.RegisterType((*WavelengthProfile)(nil), "bbf_fiber.WavelengthProfile")
}

func init() {
	proto.RegisterFile("voltha_protos/bbf_fiber_wavelength_profile_body.proto", fileDescriptor_878482202d379581)
}

var fileDescriptor_878482202d379581 = []byte{
	// 271 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x32, 0x2d, 0xcb, 0xcf, 0x29,
	0xc9, 0x48, 0x8c, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0x2f, 0xd6, 0x4f, 0x4a, 0x4a, 0x8b, 0x4f, 0xcb,
	0x4c, 0x4a, 0x2d, 0x8a, 0x2f, 0x4f, 0x2c, 0x4b, 0xcd, 0x49, 0xcd, 0x4b, 0x2f, 0xc9, 0x00, 0xc9,
	0xa5, 0x65, 0xe6, 0xa4, 0xc6, 0x27, 0xe5, 0xa7, 0x54, 0xea, 0x81, 0x15, 0x0a, 0x71, 0xc2, 0x15,
	0x4a, 0x71, 0xe5, 0xa6, 0x96, 0x24, 0x42, 0x84, 0x95, 0x0e, 0x31, 0x72, 0x89, 0x86, 0xc3, 0x35,
	0x06, 0x40, 0xf4, 0xb9, 0x24, 0x96, 0x24, 0x0a, 0x09, 0x71, 0xb1, 0xe4, 0x25, 0xe6, 0xa6, 0x4a,
	0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81, 0xd9, 0x42, 0xba, 0x5c, 0x42, 0xa5, 0x05, 0xc5, 0x25,
	0x45, 0xa9, 0x89, 0xb9, 0xf1, 0xc9, 0x19, 0x89, 0x79, 0x79, 0xa9, 0x39, 0x99, 0x29, 0x12, 0x4c,
	0x0a, 0x8c, 0x1a, 0xbc, 0x41, 0x82, 0x30, 0x19, 0x67, 0x98, 0x84, 0x90, 0x21, 0x97, 0x48, 0x4a,
	0x7e, 0x79, 0x1e, 0x86, 0x06, 0x66, 0xb0, 0x06, 0x61, 0x84, 0x1c, 0x42, 0x8b, 0x31, 0x97, 0x28,
	0x92, 0x16, 0x84, 0x97, 0x24, 0x58, 0xc0, 0x7a, 0x90, 0xcc, 0x43, 0xb8, 0x5a, 0xa9, 0x8a, 0x4b,
	0x10, 0xc3, 0x0f, 0x42, 0xa9, 0x5c, 0xe2, 0x58, 0x42, 0x24, 0x25, 0xb1, 0x24, 0x51, 0x82, 0x51,
	0x81, 0x59, 0x83, 0xdb, 0x48, 0x41, 0x0f, 0x1e, 0x24, 0x7a, 0x58, 0x83, 0xc0, 0x89, 0xfb, 0xd1,
	0xb7, 0xb3, 0xb2, 0x6c, 0x90, 0x70, 0x08, 0x12, 0x2d, 0xc7, 0xaa, 0xc6, 0x20, 0x4a, 0x2f, 0x3d,
	0xb3, 0x24, 0xa3, 0x34, 0x49, 0x2f, 0x39, 0x3f, 0x57, 0x3f, 0xbf, 0x20, 0x35, 0x2f, 0x39, 0xbf,
	0x28, 0x45, 0x1f, 0x12, 0x49, 0xba, 0xd0, 0x48, 0x4a, 0xcf, 0x47, 0xc4, 0x53, 0x12, 0x1b, 0x58,
	0xd0, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xe0, 0x29, 0xe4, 0xcc, 0xc9, 0x01, 0x00, 0x00,
}
