// Code generated by protoc-gen-go.
// source: voltha_protos/events.proto
// DO NOT EDIT!

/*
Package github_com_opencord_voltha_protos_go_voltha is a generated protocol buffer package.

It is generated from these files:
	voltha_protos/events.proto

It has these top-level messages:
	ConfigEventType
	ConfigEvent
	KpiEventType
	MetricMetaData
	MetricValuePairs
	MetricInformation
	KpiEvent
	KpiEvent2
	DeviceEvent
	EventArea
	EventCategory
	EventState
	EventType
	EventHeader
	Event
*/
package github_com_opencord_voltha_protos_go_voltha

import proto "github.com/golang/protobuf/proto"

// discarding unused import voltha "voltha_protos"
// discarding unused import google_api1 "google/api"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type ConfigEventType_ConfigEventType int32

const (
	ConfigEventType_add    ConfigEventType_ConfigEventType = 0
	ConfigEventType_remove ConfigEventType_ConfigEventType = 1
	ConfigEventType_update ConfigEventType_ConfigEventType = 2
)

var ConfigEventType_ConfigEventType_name = map[int32]string{
	0: "add",
	1: "remove",
	2: "update",
}
var ConfigEventType_ConfigEventType_value = map[string]int32{
	"add":    0,
	"remove": 1,
	"update": 2,
}

func (x ConfigEventType_ConfigEventType) String() string {
	return proto.EnumName(ConfigEventType_ConfigEventType_name, int32(x))
}

type KpiEventType_KpiEventType int32

const (
	KpiEventType_slice KpiEventType_KpiEventType = 0
	KpiEventType_ts    KpiEventType_KpiEventType = 1
)

var KpiEventType_KpiEventType_name = map[int32]string{
	0: "slice",
	1: "ts",
}
var KpiEventType_KpiEventType_value = map[string]int32{
	"slice": 0,
	"ts":    1,
}

func (x KpiEventType_KpiEventType) String() string {
	return proto.EnumName(KpiEventType_KpiEventType_name, int32(x))
}

type EventArea_EventArea int32

const (
	EventArea_COMMUNICATION EventArea_EventArea = 0
	EventArea_ENVIRONMENT   EventArea_EventArea = 1
	EventArea_EQUIPMENT     EventArea_EventArea = 2
	EventArea_SERVICE       EventArea_EventArea = 3
	EventArea_PROCESSING    EventArea_EventArea = 4
	EventArea_SECURITY      EventArea_EventArea = 5
)

var EventArea_EventArea_name = map[int32]string{
	0: "COMMUNICATION",
	1: "ENVIRONMENT",
	2: "EQUIPMENT",
	3: "SERVICE",
	4: "PROCESSING",
	5: "SECURITY",
}
var EventArea_EventArea_value = map[string]int32{
	"COMMUNICATION": 0,
	"ENVIRONMENT":   1,
	"EQUIPMENT":     2,
	"SERVICE":       3,
	"PROCESSING":    4,
	"SECURITY":      5,
}

func (x EventArea_EventArea) String() string {
	return proto.EnumName(EventArea_EventArea_name, int32(x))
}

type EventCategory_EventCategory int32

const (
	EventCategory_PON EventCategory_EventCategory = 0
	EventCategory_OLT EventCategory_EventCategory = 1
	EventCategory_ONT EventCategory_EventCategory = 2
	EventCategory_ONU EventCategory_EventCategory = 3
	EventCategory_NNI EventCategory_EventCategory = 4
)

var EventCategory_EventCategory_name = map[int32]string{
	0: "PON",
	1: "OLT",
	2: "ONT",
	3: "ONU",
	4: "NNI",
}
var EventCategory_EventCategory_value = map[string]int32{
	"PON": 0,
	"OLT": 1,
	"ONT": 2,
	"ONU": 3,
	"NNI": 4,
}

func (x EventCategory_EventCategory) String() string {
	return proto.EnumName(EventCategory_EventCategory_name, int32(x))
}

type EventState_EventState int32

const (
	EventState_UNKNOWN EventState_EventState = 0
	EventState_RAISED  EventState_EventState = 1
	EventState_CLEARED EventState_EventState = 2
)

var EventState_EventState_name = map[int32]string{
	0: "UNKNOWN",
	1: "RAISED",
	2: "CLEARED",
}
var EventState_EventState_value = map[string]int32{
	"UNKNOWN": 0,
	"RAISED":  1,
	"CLEARED": 2,
}

func (x EventState_EventState) String() string {
	return proto.EnumName(EventState_EventState_name, int32(x))
}

type EventType_EventType int32

const (
	EventType_CONFIG_EVENT EventType_EventType = 0
	EventType_KPI_EVENT    EventType_EventType = 1
	EventType_KPI_EVENT2   EventType_EventType = 2
	EventType_DEVICE_EVENT EventType_EventType = 3
)

var EventType_EventType_name = map[int32]string{
	0: "CONFIG_EVENT",
	1: "KPI_EVENT",
	2: "KPI_EVENT2",
	3: "DEVICE_EVENT",
}
var EventType_EventType_value = map[string]int32{
	"CONFIG_EVENT": 0,
	"KPI_EVENT":    1,
	"KPI_EVENT2":   2,
	"DEVICE_EVENT": 3,
}

func (x EventType_EventType) String() string {
	return proto.EnumName(EventType_EventType_name, int32(x))
}

type ConfigEventType struct {
}

func (m *ConfigEventType) Reset()         { *m = ConfigEventType{} }
func (m *ConfigEventType) String() string { return proto.CompactTextString(m) }
func (*ConfigEventType) ProtoMessage()    {}

type ConfigEvent struct {
	Type ConfigEventType_ConfigEventType `protobuf:"varint,1,opt,name=type,enum=voltha.ConfigEventType_ConfigEventType" json:"type,omitempty"`
	Hash string                          `protobuf:"bytes,2,opt,name=hash" json:"hash,omitempty"`
	Data string                          `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
}

func (m *ConfigEvent) Reset()         { *m = ConfigEvent{} }
func (m *ConfigEvent) String() string { return proto.CompactTextString(m) }
func (*ConfigEvent) ProtoMessage()    {}

type KpiEventType struct {
}

func (m *KpiEventType) Reset()         { *m = KpiEventType{} }
func (m *KpiEventType) String() string { return proto.CompactTextString(m) }
func (*KpiEventType) ProtoMessage()    {}

//
// Struct to convey a dictionary of metric metadata.
type MetricMetaData struct {
	Title           string  `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	Ts              float64 `protobuf:"fixed64,2,opt,name=ts" json:"ts,omitempty"`
	LogicalDeviceId string  `protobuf:"bytes,3,opt,name=logical_device_id" json:"logical_device_id,omitempty"`
	// (equivalent to the DPID that ONOS has
	// for the VOLTHA device without the
	//  'of:' prefix
	SerialNo string            `protobuf:"bytes,4,opt,name=serial_no" json:"serial_no,omitempty"`
	DeviceId string            `protobuf:"bytes,5,opt,name=device_id" json:"device_id,omitempty"`
	Context  map[string]string `protobuf:"bytes,6,rep,name=context" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *MetricMetaData) Reset()         { *m = MetricMetaData{} }
func (m *MetricMetaData) String() string { return proto.CompactTextString(m) }
func (*MetricMetaData) ProtoMessage()    {}

func (m *MetricMetaData) GetContext() map[string]string {
	if m != nil {
		return m.Context
	}
	return nil
}

//
// Struct to convey a dictionary of metric->value pairs. Typically used in
// pure shared-timestamp or shared-timestamp + shared object prefix situations.
type MetricValuePairs struct {
	// Metric / value pairs.
	Metrics map[string]float32 `protobuf:"bytes,1,rep,name=metrics" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"`
}

func (m *MetricValuePairs) Reset()         { *m = MetricValuePairs{} }
func (m *MetricValuePairs) String() string { return proto.CompactTextString(m) }
func (*MetricValuePairs) ProtoMessage()    {}

func (m *MetricValuePairs) GetMetrics() map[string]float32 {
	if m != nil {
		return m.Metrics
	}
	return nil
}

//
// Struct to group metadata for a metric (or group of metrics) with the key-value
// pairs of collected metrics
type MetricInformation struct {
	Metadata *MetricMetaData    `protobuf:"bytes,1,opt,name=metadata" json:"metadata,omitempty"`
	Metrics  map[string]float32 `protobuf:"bytes,2,rep,name=metrics" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"`
}

func (m *MetricInformation) Reset()         { *m = MetricInformation{} }
func (m *MetricInformation) String() string { return proto.CompactTextString(m) }
func (*MetricInformation) ProtoMessage()    {}

func (m *MetricInformation) GetMetadata() *MetricMetaData {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *MetricInformation) GetMetrics() map[string]float32 {
	if m != nil {
		return m.Metrics
	}
	return nil
}

//
// Legacy KPI Event structured.  In mid-August, the KPI event format was updated
//                               to a more easily parsable format. See VOL-1140
//                               for more information.
type KpiEvent struct {
	Type KpiEventType_KpiEventType `protobuf:"varint,1,opt,name=type,enum=voltha.KpiEventType_KpiEventType" json:"type,omitempty"`
	// Fields used when for slice:
	Ts       float32                      `protobuf:"fixed32,2,opt,name=ts" json:"ts,omitempty"`
	Prefixes map[string]*MetricValuePairs `protobuf:"bytes,3,rep,name=prefixes" json:"prefixes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *KpiEvent) Reset()         { *m = KpiEvent{} }
func (m *KpiEvent) String() string { return proto.CompactTextString(m) }
func (*KpiEvent) ProtoMessage()    {}

func (m *KpiEvent) GetPrefixes() map[string]*MetricValuePairs {
	if m != nil {
		return m.Prefixes
	}
	return nil
}

type KpiEvent2 struct {
	// Type of KPI Event
	Type KpiEventType_KpiEventType `protobuf:"varint,1,opt,name=type,enum=voltha.KpiEventType_KpiEventType" json:"type,omitempty"`
	// Fields used when for slice:
	Ts        float64              `protobuf:"fixed64,2,opt,name=ts" json:"ts,omitempty"`
	SliceData []*MetricInformation `protobuf:"bytes,3,rep,name=slice_data" json:"slice_data,omitempty"`
}

func (m *KpiEvent2) Reset()         { *m = KpiEvent2{} }
func (m *KpiEvent2) String() string { return proto.CompactTextString(m) }
func (*KpiEvent2) ProtoMessage()    {}

func (m *KpiEvent2) GetSliceData() []*MetricInformation {
	if m != nil {
		return m.SliceData
	}
	return nil
}

//
// Describes the events specific to device
type DeviceEvent struct {
	// Identifier of the originating resource of the event, for ex: device_id
	ResourceId string `protobuf:"bytes,1,opt,name=resource_id" json:"resource_id,omitempty"`
	// device_event_name indicates clearly the name of the device event
	DeviceEventName string `protobuf:"bytes,2,opt,name=device_event_name" json:"device_event_name,omitempty"`
	// Textual explanation of the device event
	Description string `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	// Key/Value storage for extra information that may give context to the event
	Context map[string]string `protobuf:"bytes,4,rep,name=context" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *DeviceEvent) Reset()         { *m = DeviceEvent{} }
func (m *DeviceEvent) String() string { return proto.CompactTextString(m) }
func (*DeviceEvent) ProtoMessage()    {}

func (m *DeviceEvent) GetContext() map[string]string {
	if m != nil {
		return m.Context
	}
	return nil
}

//
// Identify the area of the system impacted by the event.
type EventArea struct {
}

func (m *EventArea) Reset()         { *m = EventArea{} }
func (m *EventArea) String() string { return proto.CompactTextString(m) }
func (*EventArea) ProtoMessage()    {}

//
// Identify the functional category originating the event
type EventCategory struct {
}

func (m *EventCategory) Reset()         { *m = EventCategory{} }
func (m *EventCategory) String() string { return proto.CompactTextString(m) }
func (*EventCategory) ProtoMessage()    {}

//
// State of the event
type EventState struct {
}

func (m *EventState) Reset()         { *m = EventState{} }
func (m *EventState) String() string { return proto.CompactTextString(m) }
func (*EventState) ProtoMessage()    {}

//
// Identify the type of event
type EventType struct {
}

func (m *EventType) Reset()         { *m = EventType{} }
func (m *EventType) String() string { return proto.CompactTextString(m) }
func (*EventType) ProtoMessage()    {}

//
// Identify the functional category originating the event
type EventHeader struct {
	// Unique ID for this event.  e.g. voltha.some_olt.1234
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// Refers to the functional area affect by the event
	EventArea EventArea_EventArea `protobuf:"varint,2,opt,name=event_area,enum=voltha.EventArea_EventArea" json:"event_area,omitempty"`
	// Refers to functional category of the event
	Category EventCategory_EventCategory `protobuf:"varint,3,opt,name=category,enum=voltha.EventCategory_EventCategory" json:"category,omitempty"`
	// Current state of the event
	State EventState_EventState `protobuf:"varint,4,opt,name=state,enum=voltha.EventState_EventState" json:"state,omitempty"`
	// Refers to the type of the event
	Type EventType_EventType `protobuf:"varint,5,opt,name=type,enum=voltha.EventType_EventType" json:"type,omitempty"`
	// Timestamp at which the event was first raised
	RaisedTs float32 `protobuf:"fixed32,6,opt,name=raised_ts" json:"raised_ts,omitempty"`
	// Timestamp at which the event was reported
	ReportedTs float32 `protobuf:"fixed32,7,opt,name=reported_ts" json:"reported_ts,omitempty"`
	// Timestamp at which the event has changed since it was raised.
	// May be applicable only if the event has a valid EventState (not UNKNOWN).
	ChangedTs float32 `protobuf:"fixed32,8,opt,name=changed_ts" json:"changed_ts,omitempty"`
}

func (m *EventHeader) Reset()         { *m = EventHeader{} }
func (m *EventHeader) String() string { return proto.CompactTextString(m) }
func (*EventHeader) ProtoMessage()    {}

//
// Event Structure
type Event struct {
	// event header
	Header *EventHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	// Refers to ConfigEvent
	ConfigEvent *ConfigEvent `protobuf:"bytes,2,opt,name=config_event" json:"config_event,omitempty"`
	// Refers to KpiEvent
	KpiEvent *KpiEvent `protobuf:"bytes,3,opt,name=kpi_event" json:"kpi_event,omitempty"`
	// Refers to KpiEvent2
	KpiEvent2 *KpiEvent2 `protobuf:"bytes,4,opt,name=kpi_event2" json:"kpi_event2,omitempty"`
	// Refers to DeviceEvent
	DeviceEvent *DeviceEvent `protobuf:"bytes,5,opt,name=device_event" json:"device_event,omitempty"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}

func (m *Event) GetHeader() *EventHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Event) GetConfigEvent() *ConfigEvent {
	if m != nil {
		return m.ConfigEvent
	}
	return nil
}

func (m *Event) GetKpiEvent() *KpiEvent {
	if m != nil {
		return m.KpiEvent
	}
	return nil
}

func (m *Event) GetKpiEvent2() *KpiEvent2 {
	if m != nil {
		return m.KpiEvent2
	}
	return nil
}

func (m *Event) GetDeviceEvent() *DeviceEvent {
	if m != nil {
		return m.DeviceEvent
	}
	return nil
}

func init() {
	proto.RegisterEnum("voltha.ConfigEventType_ConfigEventType", ConfigEventType_ConfigEventType_name, ConfigEventType_ConfigEventType_value)
	proto.RegisterEnum("voltha.KpiEventType_KpiEventType", KpiEventType_KpiEventType_name, KpiEventType_KpiEventType_value)
	proto.RegisterEnum("voltha.EventArea_EventArea", EventArea_EventArea_name, EventArea_EventArea_value)
	proto.RegisterEnum("voltha.EventCategory_EventCategory", EventCategory_EventCategory_name, EventCategory_EventCategory_value)
	proto.RegisterEnum("voltha.EventState_EventState", EventState_EventState_name, EventState_EventState_value)
	proto.RegisterEnum("voltha.EventType_EventType", EventType_EventType_name, EventType_EventType_value)
}
