// Code generated by protoc-gen-go. DO NOT EDIT.
// source: voltha_protos/on_demand_api.proto

package voltha

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//option (common.yang_child_rule) = MOVE_TO_PARENT_LEVEL;
type TestCode_TestResponseResult int32

const (
	TestCode_SUCCESS TestCode_TestResponseResult = 0
	TestCode_FAILURE TestCode_TestResponseResult = 1
)

var TestCode_TestResponseResult_name = map[int32]string{
	0: "SUCCESS",
	1: "FAILURE",
}

var TestCode_TestResponseResult_value = map[string]int32{
	"SUCCESS": 0,
	"FAILURE": 1,
}

func (x TestCode_TestResponseResult) String() string {
	return proto.EnumName(TestCode_TestResponseResult_name, int32(x))
}

func (TestCode_TestResponseResult) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_98edfae8a8d0d91b, []int{2, 0}
}

// OnDemandTestAPi Request paramaters
type OnuID struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OnuID) Reset()         { *m = OnuID{} }
func (m *OnuID) String() string { return proto.CompactTextString(m) }
func (*OnuID) ProtoMessage()    {}
func (*OnuID) Descriptor() ([]byte, []int) {
	return fileDescriptor_98edfae8a8d0d91b, []int{0}
}

func (m *OnuID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnuID.Unmarshal(m, b)
}
func (m *OnuID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnuID.Marshal(b, m, deterministic)
}
func (m *OnuID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnuID.Merge(m, src)
}
func (m *OnuID) XXX_Size() int {
	return xxx_messageInfo_OnuID.Size(m)
}
func (m *OnuID) XXX_DiscardUnknown() {
	xxx_messageInfo_OnuID.DiscardUnknown(m)
}

var xxx_messageInfo_OnuID proto.InternalMessageInfo

func (m *OnuID) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ResponseTest struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseTest) Reset()         { *m = ResponseTest{} }
func (m *ResponseTest) String() string { return proto.CompactTextString(m) }
func (*ResponseTest) ProtoMessage()    {}
func (*ResponseTest) Descriptor() ([]byte, []int) {
	return fileDescriptor_98edfae8a8d0d91b, []int{1}
}

func (m *ResponseTest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseTest.Unmarshal(m, b)
}
func (m *ResponseTest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseTest.Marshal(b, m, deterministic)
}
func (m *ResponseTest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseTest.Merge(m, src)
}
func (m *ResponseTest) XXX_Size() int {
	return xxx_messageInfo_ResponseTest.Size(m)
}
func (m *ResponseTest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseTest.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseTest proto.InternalMessageInfo

func (m *ResponseTest) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

// Omci Test Response message format
type TestCode struct {
	Result               TestCode_TestResponseResult `protobuf:"varint,1,opt,name=result,proto3,enum=voltha.TestCode_TestResponseResult" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *TestCode) Reset()         { *m = TestCode{} }
func (m *TestCode) String() string { return proto.CompactTextString(m) }
func (*TestCode) ProtoMessage()    {}
func (*TestCode) Descriptor() ([]byte, []int) {
	return fileDescriptor_98edfae8a8d0d91b, []int{2}
}

func (m *TestCode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestCode.Unmarshal(m, b)
}
func (m *TestCode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestCode.Marshal(b, m, deterministic)
}
func (m *TestCode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestCode.Merge(m, src)
}
func (m *TestCode) XXX_Size() int {
	return xxx_messageInfo_TestCode.Size(m)
}
func (m *TestCode) XXX_DiscardUnknown() {
	xxx_messageInfo_TestCode.DiscardUnknown(m)
}

var xxx_messageInfo_TestCode proto.InternalMessageInfo

func (m *TestCode) GetResult() TestCode_TestResponseResult {
	if m != nil {
		return m.Result
	}
	return TestCode_SUCCESS
}

func init() {
	proto.RegisterEnum("voltha.TestCode_TestResponseResult", TestCode_TestResponseResult_name, TestCode_TestResponseResult_value)
	proto.RegisterType((*OnuID)(nil), "voltha.OnuID")
	proto.RegisterType((*ResponseTest)(nil), "voltha.ResponseTest")
	proto.RegisterType((*TestCode)(nil), "voltha.TestCode")
}

func init() { proto.RegisterFile("voltha_protos/on_demand_api.proto", fileDescriptor_98edfae8a8d0d91b) }

var fileDescriptor_98edfae8a8d0d91b = []byte{
	// 337 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0xcd, 0x4a, 0xc3, 0x40,
	0x14, 0x85, 0x4d, 0xc1, 0x5a, 0xa7, 0x5a, 0x4a, 0x10, 0x2b, 0xa5, 0x0b, 0x8d, 0x20, 0x22, 0x74,
	0x82, 0xed, 0x4e, 0x57, 0xb6, 0x56, 0x28, 0x68, 0x5b, 0x12, 0xeb, 0x42, 0x17, 0x61, 0x9a, 0x5c,
	0xd2, 0x81, 0x64, 0x6e, 0xc8, 0x4c, 0x63, 0xdd, 0xfa, 0x0a, 0x3e, 0x9a, 0xaf, 0xe0, 0x83, 0x48,
	0x27, 0x89, 0x28, 0xee, 0xe6, 0x9c, 0xfb, 0x71, 0xee, 0xcf, 0x90, 0x93, 0x0c, 0x23, 0xb5, 0x64,
	0x5e, 0x92, 0xa2, 0x42, 0x69, 0xa3, 0xf0, 0x02, 0x88, 0x99, 0x08, 0x3c, 0x96, 0x70, 0xaa, 0x4d,
	0xb3, 0x9a, 0x23, 0xed, 0x4e, 0x88, 0x18, 0x46, 0x60, 0xb3, 0x84, 0xdb, 0x4c, 0x08, 0x54, 0x4c,
	0x71, 0x14, 0x32, 0xa7, 0xac, 0x16, 0xd9, 0x9e, 0x8a, 0xd5, 0xf8, 0xd6, 0x6c, 0x90, 0x0a, 0x0f,
	0x8e, 0x8c, 0x63, 0xe3, 0x7c, 0xd7, 0xa9, 0xf0, 0xc0, 0x3a, 0x23, 0x7b, 0x0e, 0xc8, 0x04, 0x85,
	0x84, 0x47, 0x90, 0xca, 0x3c, 0x24, 0xd5, 0x14, 0xe4, 0x2a, 0x52, 0x05, 0x53, 0x28, 0xeb, 0x95,
	0xd4, 0x36, 0xf5, 0x21, 0x06, 0x60, 0x5e, 0xff, 0x61, 0x1a, 0xbd, 0x53, 0x9a, 0xcf, 0x40, 0x4b,
	0x42, 0x3f, 0xca, 0x58, 0x47, 0xa3, 0x3f, 0x41, 0x94, 0x98, 0xff, 0xab, 0x66, 0x9d, 0xec, 0xb8,
	0xf3, 0xe1, 0x70, 0xe4, 0xba, 0xcd, 0xad, 0x8d, 0xb8, 0xbb, 0x19, 0xdf, 0xcf, 0x9d, 0x51, 0xd3,
	0xe8, 0x31, 0x42, 0x26, 0x10, 0xbb, 0x90, 0x66, 0xdc, 0x07, 0xd3, 0x25, 0xb5, 0x69, 0xec, 0x73,
	0x3d, 0xea, 0x7e, 0xd9, 0x56, 0x6f, 0xd6, 0x3e, 0x28, 0xe5, 0xef, 0x7d, 0x2c, 0xeb, 0xfd, 0xf3,
	0xeb, 0xa3, 0xd2, 0xb1, 0x5a, 0xfa, 0x30, 0xd9, 0xa5, 0x2d, 0x15, 0x4b, 0x95, 0x87, 0xb1, 0xcf,
	0x3d, 0x05, 0x52, 0x5d, 0x19, 0x17, 0x83, 0x17, 0xd2, 0xe6, 0x48, 0xc3, 0x34, 0xf1, 0x29, 0xac,
	0x59, 0x9c, 0x44, 0x20, 0xe9, 0x64, 0xf4, 0xd0, 0x9d, 0xa5, 0xb8, 0x7e, 0x1b, 0xd4, 0x9f, 0x74,
	0xec, 0x6c, 0x73, 0xc7, 0x99, 0xf1, 0x4c, 0x43, 0xae, 0x96, 0xab, 0x05, 0xf5, 0x31, 0xb6, 0x31,
	0x01, 0xe1, 0x63, 0x1a, 0xd8, 0x79, 0xe7, 0x6e, 0xf1, 0x4d, 0x59, 0xdf, 0x0e, 0xb1, 0xf0, 0x16,
	0x55, 0x6d, 0xf6, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0xbd, 0x54, 0x5b, 0x82, 0xcb, 0x01, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NemServiceClient is the client API for NemService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NemServiceClient interface {
	// On Demand API for Omci Test Action
	OmciTest(ctx context.Context, in *OnuID, opts ...grpc.CallOption) (*ResponseTest, error)
}

type nemServiceClient struct {
	cc *grpc.ClientConn
}

func NewNemServiceClient(cc *grpc.ClientConn) NemServiceClient {
	return &nemServiceClient{cc}
}

func (c *nemServiceClient) OmciTest(ctx context.Context, in *OnuID, opts ...grpc.CallOption) (*ResponseTest, error) {
	out := new(ResponseTest)
	err := c.cc.Invoke(ctx, "/voltha.NemService/OmciTest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NemServiceServer is the server API for NemService service.
type NemServiceServer interface {
	// On Demand API for Omci Test Action
	OmciTest(context.Context, *OnuID) (*ResponseTest, error)
}

func RegisterNemServiceServer(s *grpc.Server, srv NemServiceServer) {
	s.RegisterService(&_NemService_serviceDesc, srv)
}

func _NemService_OmciTest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnuID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NemServiceServer).OmciTest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/voltha.NemService/OmciTest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NemServiceServer).OmciTest(ctx, req.(*OnuID))
	}
	return interceptor(ctx, in, info, handler)
}

var _NemService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "voltha.NemService",
	HandlerType: (*NemServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OmciTest",
			Handler:    _NemService_OmciTest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "voltha_protos/on_demand_api.proto",
}
