// Code generated by protoc-gen-go. DO NOT EDIT.
// source: voltha_protos/service_profile.proto

package service_profile

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	common "github.com/opencord/voltha-protos/v5/go/common"
	tech_profile "github.com/opencord/voltha-protos/v5/go/tech_profile"
	voip_profile "github.com/opencord/voltha-protos/v5/go/voip_profile"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Key from public import voltha_protos/common.proto
type Key = common.Key

// ID from public import voltha_protos/common.proto
type ID = common.ID

// IDs from public import voltha_protos/common.proto
type IDs = common.IDs

// AdminState from public import voltha_protos/common.proto
type AdminState = common.AdminState

// OperStatus from public import voltha_protos/common.proto
type OperStatus = common.OperStatus

// ConnectStatus from public import voltha_protos/common.proto
type ConnectStatus = common.ConnectStatus

// OperationResp from public import voltha_protos/common.proto
type OperationResp = common.OperationResp

// TestModeKeys from public import voltha_protos/common.proto
type TestModeKeys = common.TestModeKeys

var TestModeKeys_name = common.TestModeKeys_name
var TestModeKeys_value = common.TestModeKeys_value

const TestModeKeys_api_test = TestModeKeys(common.TestModeKeys_api_test)

// AdminState_Types from public import voltha_protos/common.proto
type AdminState_Types = common.AdminState_Types

var AdminState_Types_name = common.AdminState_Types_name
var AdminState_Types_value = common.AdminState_Types_value

const AdminState_UNKNOWN = AdminState_Types(common.AdminState_UNKNOWN)
const AdminState_PREPROVISIONED = AdminState_Types(common.AdminState_PREPROVISIONED)
const AdminState_ENABLED = AdminState_Types(common.AdminState_ENABLED)
const AdminState_DISABLED = AdminState_Types(common.AdminState_DISABLED)
const AdminState_DOWNLOADING_IMAGE = AdminState_Types(common.AdminState_DOWNLOADING_IMAGE)

// OperStatus_Types from public import voltha_protos/common.proto
type OperStatus_Types = common.OperStatus_Types

var OperStatus_Types_name = common.OperStatus_Types_name
var OperStatus_Types_value = common.OperStatus_Types_value

const OperStatus_UNKNOWN = OperStatus_Types(common.OperStatus_UNKNOWN)
const OperStatus_DISCOVERED = OperStatus_Types(common.OperStatus_DISCOVERED)
const OperStatus_ACTIVATING = OperStatus_Types(common.OperStatus_ACTIVATING)
const OperStatus_TESTING = OperStatus_Types(common.OperStatus_TESTING)
const OperStatus_ACTIVE = OperStatus_Types(common.OperStatus_ACTIVE)
const OperStatus_FAILED = OperStatus_Types(common.OperStatus_FAILED)
const OperStatus_RECONCILING = OperStatus_Types(common.OperStatus_RECONCILING)
const OperStatus_RECONCILING_FAILED = OperStatus_Types(common.OperStatus_RECONCILING_FAILED)

// ConnectStatus_Types from public import voltha_protos/common.proto
type ConnectStatus_Types = common.ConnectStatus_Types

var ConnectStatus_Types_name = common.ConnectStatus_Types_name
var ConnectStatus_Types_value = common.ConnectStatus_Types_value

const ConnectStatus_UNKNOWN = ConnectStatus_Types(common.ConnectStatus_UNKNOWN)
const ConnectStatus_UNREACHABLE = ConnectStatus_Types(common.ConnectStatus_UNREACHABLE)
const ConnectStatus_REACHABLE = ConnectStatus_Types(common.ConnectStatus_REACHABLE)

// OperationResp_OperationReturnCode from public import voltha_protos/common.proto
type OperationResp_OperationReturnCode = common.OperationResp_OperationReturnCode

var OperationResp_OperationReturnCode_name = common.OperationResp_OperationReturnCode_name
var OperationResp_OperationReturnCode_value = common.OperationResp_OperationReturnCode_value

const OperationResp_OPERATION_SUCCESS = OperationResp_OperationReturnCode(common.OperationResp_OPERATION_SUCCESS)
const OperationResp_OPERATION_FAILURE = OperationResp_OperationReturnCode(common.OperationResp_OPERATION_FAILURE)
const OperationResp_OPERATION_UNSUPPORTED = OperationResp_OperationReturnCode(common.OperationResp_OPERATION_UNSUPPORTED)
const OperationResp_OPERATION_IN_PROGRESS = OperationResp_OperationReturnCode(common.OperationResp_OPERATION_IN_PROGRESS)

// SchedulerConfig from public import voltha_protos/tech_profile.proto
type SchedulerConfig = tech_profile.SchedulerConfig

// TrafficShapingInfo from public import voltha_protos/tech_profile.proto
type TrafficShapingInfo = tech_profile.TrafficShapingInfo

// TrafficScheduler from public import voltha_protos/tech_profile.proto
type TrafficScheduler = tech_profile.TrafficScheduler

// TrafficSchedulers from public import voltha_protos/tech_profile.proto
type TrafficSchedulers = tech_profile.TrafficSchedulers

// TailDropDiscardConfig from public import voltha_protos/tech_profile.proto
type TailDropDiscardConfig = tech_profile.TailDropDiscardConfig

// RedDiscardConfig from public import voltha_protos/tech_profile.proto
type RedDiscardConfig = tech_profile.RedDiscardConfig

// WRedDiscardConfig from public import voltha_protos/tech_profile.proto
type WRedDiscardConfig = tech_profile.WRedDiscardConfig

// DiscardConfig from public import voltha_protos/tech_profile.proto
type DiscardConfig = tech_profile.DiscardConfig
type DiscardConfig_TailDropDiscardConfig = tech_profile.DiscardConfig_TailDropDiscardConfig
type DiscardConfig_RedDiscardConfig = tech_profile.DiscardConfig_RedDiscardConfig
type DiscardConfig_WredDiscardConfig = tech_profile.DiscardConfig_WredDiscardConfig

// TrafficQueue from public import voltha_protos/tech_profile.proto
type TrafficQueue = tech_profile.TrafficQueue

// TrafficQueues from public import voltha_protos/tech_profile.proto
type TrafficQueues = tech_profile.TrafficQueues

// InstanceControl from public import voltha_protos/tech_profile.proto
type InstanceControl = tech_profile.InstanceControl

// QThresholds from public import voltha_protos/tech_profile.proto
type QThresholds = tech_profile.QThresholds

// GemPortAttributes from public import voltha_protos/tech_profile.proto
type GemPortAttributes = tech_profile.GemPortAttributes

// SchedulerAttributes from public import voltha_protos/tech_profile.proto
type SchedulerAttributes = tech_profile.SchedulerAttributes

// EPONQueueAttributes from public import voltha_protos/tech_profile.proto
type EPONQueueAttributes = tech_profile.EPONQueueAttributes

// TechProfile from public import voltha_protos/tech_profile.proto
type TechProfile = tech_profile.TechProfile

// EponTechProfile from public import voltha_protos/tech_profile.proto
type EponTechProfile = tech_profile.EponTechProfile

// TechProfileInstance from public import voltha_protos/tech_profile.proto
type TechProfileInstance = tech_profile.TechProfileInstance

// EponTechProfileInstance from public import voltha_protos/tech_profile.proto
type EponTechProfileInstance = tech_profile.EponTechProfileInstance

// ResourceInstance from public import voltha_protos/tech_profile.proto
type ResourceInstance = tech_profile.ResourceInstance

// Direction from public import voltha_protos/tech_profile.proto
type Direction = tech_profile.Direction

var Direction_name = tech_profile.Direction_name
var Direction_value = tech_profile.Direction_value

const Direction_UPSTREAM = Direction(tech_profile.Direction_UPSTREAM)
const Direction_DOWNSTREAM = Direction(tech_profile.Direction_DOWNSTREAM)
const Direction_BIDIRECTIONAL = Direction(tech_profile.Direction_BIDIRECTIONAL)

// SchedulingPolicy from public import voltha_protos/tech_profile.proto
type SchedulingPolicy = tech_profile.SchedulingPolicy

var SchedulingPolicy_name = tech_profile.SchedulingPolicy_name
var SchedulingPolicy_value = tech_profile.SchedulingPolicy_value

const SchedulingPolicy_WRR = SchedulingPolicy(tech_profile.SchedulingPolicy_WRR)
const SchedulingPolicy_StrictPriority = SchedulingPolicy(tech_profile.SchedulingPolicy_StrictPriority)
const SchedulingPolicy_Hybrid = SchedulingPolicy(tech_profile.SchedulingPolicy_Hybrid)

// AdditionalBW from public import voltha_protos/tech_profile.proto
type AdditionalBW = tech_profile.AdditionalBW

var AdditionalBW_name = tech_profile.AdditionalBW_name
var AdditionalBW_value = tech_profile.AdditionalBW_value

const AdditionalBW_AdditionalBW_None = AdditionalBW(tech_profile.AdditionalBW_AdditionalBW_None)
const AdditionalBW_AdditionalBW_NA = AdditionalBW(tech_profile.AdditionalBW_AdditionalBW_NA)
const AdditionalBW_AdditionalBW_BestEffort = AdditionalBW(tech_profile.AdditionalBW_AdditionalBW_BestEffort)
const AdditionalBW_AdditionalBW_Auto = AdditionalBW(tech_profile.AdditionalBW_AdditionalBW_Auto)

// DiscardPolicy from public import voltha_protos/tech_profile.proto
type DiscardPolicy = tech_profile.DiscardPolicy

var DiscardPolicy_name = tech_profile.DiscardPolicy_name
var DiscardPolicy_value = tech_profile.DiscardPolicy_value

const DiscardPolicy_TailDrop = DiscardPolicy(tech_profile.DiscardPolicy_TailDrop)
const DiscardPolicy_WTailDrop = DiscardPolicy(tech_profile.DiscardPolicy_WTailDrop)
const DiscardPolicy_Red = DiscardPolicy(tech_profile.DiscardPolicy_Red)
const DiscardPolicy_WRed = DiscardPolicy(tech_profile.DiscardPolicy_WRed)

// InferredAdditionBWIndication from public import voltha_protos/tech_profile.proto
type InferredAdditionBWIndication = tech_profile.InferredAdditionBWIndication

var InferredAdditionBWIndication_name = tech_profile.InferredAdditionBWIndication_name
var InferredAdditionBWIndication_value = tech_profile.InferredAdditionBWIndication_value

const InferredAdditionBWIndication_InferredAdditionBWIndication_None = InferredAdditionBWIndication(tech_profile.InferredAdditionBWIndication_InferredAdditionBWIndication_None)
const InferredAdditionBWIndication_InferredAdditionBWIndication_Assured = InferredAdditionBWIndication(tech_profile.InferredAdditionBWIndication_InferredAdditionBWIndication_Assured)
const InferredAdditionBWIndication_InferredAdditionBWIndication_BestEffort = InferredAdditionBWIndication(tech_profile.InferredAdditionBWIndication_InferredAdditionBWIndication_BestEffort)

// VoipUserProfile from public import voltha_protos/voip_profile.proto
type VoipUserProfile = voip_profile.VoipUserProfile

// VoipSystemProfile from public import voltha_protos/voip_profile.proto
type VoipSystemProfile = voip_profile.VoipSystemProfile

// VoipConfig from public import voltha_protos/voip_profile.proto
type VoipConfig = voip_profile.VoipConfig

// IpHostConfig from public import voltha_protos/voip_profile.proto
type IpHostConfig = voip_profile.IpHostConfig

// TcpUdpConfig from public import voltha_protos/voip_profile.proto
type TcpUdpConfig = voip_profile.TcpUdpConfig

// VoipVoiceCtp from public import voltha_protos/voip_profile.proto
type VoipVoiceCtp = voip_profile.VoipVoiceCtp

// VoipMediaProfile from public import voltha_protos/voip_profile.proto
type VoipMediaProfile = voip_profile.VoipMediaProfile

// VoiceServiceProfile from public import voltha_protos/voip_profile.proto
type VoiceServiceProfile = voip_profile.VoiceServiceProfile

// RtpProfile from public import voltha_protos/voip_profile.proto
type RtpProfile = voip_profile.RtpProfile

// PptpPotsUni from public import voltha_protos/voip_profile.proto
type PptpPotsUni = voip_profile.PptpPotsUni

// SipConfig from public import voltha_protos/voip_profile.proto
type SipConfig = voip_profile.SipConfig

// SipUserData from public import voltha_protos/voip_profile.proto
type SipUserData = voip_profile.SipUserData

// SipAgentConfig from public import voltha_protos/voip_profile.proto
type SipAgentConfig = voip_profile.SipAgentConfig

// NetworkDialPlan from public import voltha_protos/voip_profile.proto
type NetworkDialPlan = voip_profile.NetworkDialPlan

// UsernameAndPassword from public import voltha_protos/voip_profile.proto
type UsernameAndPassword = voip_profile.UsernameAndPassword

// SipResponseTable from public import voltha_protos/voip_profile.proto
type SipResponseTable = voip_profile.SipResponseTable

// DialPlanTable from public import voltha_protos/voip_profile.proto
type DialPlanTable = voip_profile.DialPlanTable

// VoipFeatureAccessCodes from public import voltha_protos/voip_profile.proto
type VoipFeatureAccessCodes = voip_profile.VoipFeatureAccessCodes

// VoipApplicationServiceProfile from public import voltha_protos/voip_profile.proto
type VoipApplicationServiceProfile = voip_profile.VoipApplicationServiceProfile

// A generic profile message that is designed to be used in voltha API in order to save profiles into voltha KV
type ServiceProfile struct {
	// Path for KV store
	Key *common.Key `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// The value to be inserted into DB
	ServiceProfileData   *ServiceProfileData `protobuf:"bytes,2,opt,name=serviceProfileData,proto3" json:"serviceProfileData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ServiceProfile) Reset()         { *m = ServiceProfile{} }
func (m *ServiceProfile) String() string { return proto.CompactTextString(m) }
func (*ServiceProfile) ProtoMessage()    {}
func (*ServiceProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_55da64a81f9dc61f, []int{0}
}

func (m *ServiceProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceProfile.Unmarshal(m, b)
}
func (m *ServiceProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceProfile.Marshal(b, m, deterministic)
}
func (m *ServiceProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceProfile.Merge(m, src)
}
func (m *ServiceProfile) XXX_Size() int {
	return xxx_messageInfo_ServiceProfile.Size(m)
}
func (m *ServiceProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceProfile.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceProfile proto.InternalMessageInfo

func (m *ServiceProfile) GetKey() *common.Key {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *ServiceProfile) GetServiceProfileData() *ServiceProfileData {
	if m != nil {
		return m.ServiceProfileData
	}
	return nil
}

type ServiceProfileData struct {
	// Types that are valid to be assigned to Data:
	//	*ServiceProfileData_VoipSystemProfile
	//	*ServiceProfileData_VoipUserProfile
	//	*ServiceProfileData_TechProfile
	//	*ServiceProfileData_EponTechProfile
	Data                 isServiceProfileData_Data `protobuf_oneof:"data"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ServiceProfileData) Reset()         { *m = ServiceProfileData{} }
func (m *ServiceProfileData) String() string { return proto.CompactTextString(m) }
func (*ServiceProfileData) ProtoMessage()    {}
func (*ServiceProfileData) Descriptor() ([]byte, []int) {
	return fileDescriptor_55da64a81f9dc61f, []int{1}
}

func (m *ServiceProfileData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceProfileData.Unmarshal(m, b)
}
func (m *ServiceProfileData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceProfileData.Marshal(b, m, deterministic)
}
func (m *ServiceProfileData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceProfileData.Merge(m, src)
}
func (m *ServiceProfileData) XXX_Size() int {
	return xxx_messageInfo_ServiceProfileData.Size(m)
}
func (m *ServiceProfileData) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceProfileData.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceProfileData proto.InternalMessageInfo

type isServiceProfileData_Data interface {
	isServiceProfileData_Data()
}

type ServiceProfileData_VoipSystemProfile struct {
	VoipSystemProfile *voip_profile.VoipSystemProfile `protobuf:"bytes,2,opt,name=voipSystemProfile,proto3,oneof"`
}

type ServiceProfileData_VoipUserProfile struct {
	VoipUserProfile *voip_profile.VoipUserProfile `protobuf:"bytes,3,opt,name=voipUserProfile,proto3,oneof"`
}

type ServiceProfileData_TechProfile struct {
	TechProfile *tech_profile.TechProfile `protobuf:"bytes,4,opt,name=techProfile,proto3,oneof"`
}

type ServiceProfileData_EponTechProfile struct {
	EponTechProfile *tech_profile.EponTechProfile `protobuf:"bytes,5,opt,name=eponTechProfile,proto3,oneof"`
}

func (*ServiceProfileData_VoipSystemProfile) isServiceProfileData_Data() {}

func (*ServiceProfileData_VoipUserProfile) isServiceProfileData_Data() {}

func (*ServiceProfileData_TechProfile) isServiceProfileData_Data() {}

func (*ServiceProfileData_EponTechProfile) isServiceProfileData_Data() {}

func (m *ServiceProfileData) GetData() isServiceProfileData_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ServiceProfileData) GetVoipSystemProfile() *voip_profile.VoipSystemProfile {
	if x, ok := m.GetData().(*ServiceProfileData_VoipSystemProfile); ok {
		return x.VoipSystemProfile
	}
	return nil
}

func (m *ServiceProfileData) GetVoipUserProfile() *voip_profile.VoipUserProfile {
	if x, ok := m.GetData().(*ServiceProfileData_VoipUserProfile); ok {
		return x.VoipUserProfile
	}
	return nil
}

func (m *ServiceProfileData) GetTechProfile() *tech_profile.TechProfile {
	if x, ok := m.GetData().(*ServiceProfileData_TechProfile); ok {
		return x.TechProfile
	}
	return nil
}

func (m *ServiceProfileData) GetEponTechProfile() *tech_profile.EponTechProfile {
	if x, ok := m.GetData().(*ServiceProfileData_EponTechProfile); ok {
		return x.EponTechProfile
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ServiceProfileData) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ServiceProfileData_VoipSystemProfile)(nil),
		(*ServiceProfileData_VoipUserProfile)(nil),
		(*ServiceProfileData_TechProfile)(nil),
		(*ServiceProfileData_EponTechProfile)(nil),
	}
}

func init() {
	proto.RegisterType((*ServiceProfile)(nil), "service_profile.ServiceProfile")
	proto.RegisterType((*ServiceProfileData)(nil), "service_profile.ServiceProfileData")
}

func init() {
	proto.RegisterFile("voltha_protos/service_profile.proto", fileDescriptor_55da64a81f9dc61f)
}

var fileDescriptor_55da64a81f9dc61f = []byte{
	// 339 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0x3f, 0x4f, 0xc3, 0x30,
	0x10, 0xc5, 0x9b, 0xb6, 0x74, 0x70, 0x25, 0x2a, 0x3c, 0x95, 0x8a, 0x8a, 0xaa, 0x5d, 0x58, 0xb0,
	0x25, 0x10, 0x62, 0x62, 0xa9, 0x40, 0x2a, 0x62, 0x20, 0x4a, 0x80, 0x81, 0x01, 0xe4, 0xa6, 0x26,
	0xb5, 0x68, 0x7d, 0x51, 0x6c, 0x22, 0x65, 0xe7, 0x93, 0xf1, 0xc9, 0x90, 0xf3, 0x47, 0xc4, 0x0e,
	0x63, 0xee, 0x7e, 0xef, 0xdd, 0x73, 0xee, 0xd0, 0x22, 0x83, 0x9d, 0xde, 0xb2, 0xf7, 0x24, 0x05,
	0x0d, 0x8a, 0x2a, 0x9e, 0x66, 0x22, 0xe2, 0xe6, 0xf3, 0x43, 0xec, 0x38, 0x29, 0xca, 0x78, 0xe4,
	0x94, 0x27, 0x27, 0x31, 0x40, 0xbc, 0xe3, 0x94, 0x25, 0x82, 0x32, 0x29, 0x41, 0x33, 0x2d, 0x40,
	0xaa, 0x12, 0x9f, 0x4c, 0x6c, 0xcf, 0x08, 0xf6, 0x7b, 0x90, 0x55, 0x6f, 0x66, 0xf7, 0x34, 0x8f,
	0xb6, 0xf6, 0x30, 0x97, 0xc8, 0x40, 0x24, 0x36, 0x31, 0xff, 0xf6, 0xd0, 0x61, 0x58, 0x26, 0xf2,
	0xcb, 0x06, 0x9e, 0xa2, 0xde, 0x27, 0xcf, 0xc7, 0xde, 0xcc, 0x3b, 0x1b, 0x5e, 0x0c, 0x49, 0x35,
	0xf2, 0x81, 0xe7, 0x81, 0xa9, 0xe3, 0x10, 0x61, 0x65, 0x09, 0x6e, 0x99, 0x66, 0xe3, 0x6e, 0x41,
	0x2f, 0x88, 0xfb, 0xe8, 0xb0, 0x85, 0x06, 0xff, 0xc8, 0xe7, 0x3f, 0x5d, 0x84, 0xdb, 0x28, 0x7e,
	0x44, 0x47, 0x26, 0x73, 0x98, 0x2b, 0xcd, 0xf7, 0x55, 0xa3, 0x1a, 0x75, 0x4a, 0xac, 0xd7, 0xbc,
	0xb8, 0xd8, 0xaa, 0x13, 0xb4, 0xb5, 0xf8, 0x1e, 0x8d, 0x4c, 0xf1, 0x59, 0xf1, 0xb4, 0xb6, 0xeb,
	0x15, 0x76, 0xd3, 0xb6, 0x5d, 0x03, 0x5a, 0x75, 0x02, 0x57, 0x87, 0x6f, 0xd0, 0xd0, 0xfc, 0xf1,
	0xda, 0xa6, 0x5f, 0xd8, 0x1c, 0x13, 0x6b, 0x0b, 0x4f, 0x7f, 0xc0, 0xaa, 0x13, 0x34, 0x79, 0x93,
	0x84, 0x27, 0x20, 0x1b, 0xc4, 0xf8, 0xa0, 0x4a, 0x62, 0x59, 0xdc, 0xd9, 0x90, 0x49, 0xe2, 0xe8,
	0x96, 0x03, 0xd4, 0xdf, 0x30, 0xcd, 0x96, 0x6f, 0x68, 0x01, 0x69, 0x4c, 0x20, 0xe1, 0x32, 0x82,
	0x74, 0x43, 0xca, 0xe5, 0xbb, 0x2b, 0x79, 0xbd, 0x8e, 0x85, 0xde, 0x7e, 0xad, 0xcd, 0x62, 0x69,
	0xcd, 0xd2, 0x92, 0x3d, 0xaf, 0x0f, 0xe5, 0x8a, 0xc6, 0xe0, 0x1e, 0xb0, 0xef, 0xf9, 0x5d, 0xbf,
	0xb7, 0x1e, 0x14, 0xcc, 0xe5, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf0, 0xc4, 0xb3, 0x3c, 0xee,
	0x02, 0x00, 0x00,
}
